services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar-reminder-telegram-bot
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./data:/app/data
    env_file:
      - path: ./.env
        required: false
